# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: ${buildPlatform}
  buildConfiguration: ${buildConfiguration}

strategy:
  maxParallel: 1
  matrix: 
      Debug64:
          Configuration: Debug
          Platform: x64
      Release64:
          Configuration: Release
          Platform: x64
      Debug86:
          Configuration: Debug
          Platform: x86
      Release86:
          Configuration: Release
          Platform: x86
steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      vsVersion: '15.0'
      platform: '$(Platform)'
      configuration: '$(Configuration)'

  - task: VSTest@2
    inputs:
      platform: '$(Platform)'
      configuration: '$(Configuration)'

  - task: CopyFiles@2
    inputs:
      Contents: '**\$(Configuration)\**\?(*.exe|*.dll|*.pdb)'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\$(System.JobName)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: $(System.JobName)
